# Generated by Django 4.1.3 on 2023-01-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
