# Generated by Django 4.1.3 on 2023-01-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customers_address_alter_customers_phone_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customer_tb',
        ),
    ]
