# Generated by Django 4.1.3 on 2023-01-06 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_customers_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
    ]
