# Generated by Django 4.1.3 on 2023-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_phone_number_customers_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.IntegerField(default=0)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_branch', models.CharField(max_length=40)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
