# Generated by Django 4.1.5 on 2023-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
