# Generated by Django 4.1.7 on 2023-03-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='s_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
